name: demo-test

on:
  workflow_dispatch:
  schedule:
    - cron: "59 16 * * *"
  push:
    branches:
      - feat/github-actions**

jobs:
  demo-test:
    runs-on: ubuntu-latest

    steps:
      - name: Demo README's instructions
        run: |
          npm install -g serverless@^3
          sls create --template-url "https://github.com/wyltele/docker-selenium-lambda/tree/main" --path docker-selenium-lambda && cd $_
          sls deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
